transformer_xl:
  n_layer: 6
  n_head: 8
  cutoffs: [2222, 4444, 22222]
  return_dict: True
  mem_len: 0

transformer_xl_tokenizer:
  path: "data/tokenizer-xl-wiki2"

compressive_transformer:
  n_layer: 4
  n_head: 8
  compression_rate: 3
  c_mem_length: 4
  mem_len: 2
  return_dict: True
  output_hidden_states: True
  cutoffs: [2222, 4444, 22222]

gpt:
  n_layer: 12

gpt_tokenizer:
  vocab_file: "data/tokenizer-gpt-wiki2/vocab.json"
  merges_file: "data/tokenizer-gpt-wiki2/merges.txt"
  unk_token: "<unk>"

data_loader:
  samples: 
  valid_samples: 640
  batch_size: 8
  max_length: 32

optimizer: 
  learning_rate: 0.0001

train:
  epochs: 50
  subsequence_len: 32
  aggregate: 4